export const CHAT_CONNECT_REQUEST = 'CHAT_CONNECT_REQUEST';
export const CHAT_CONNECT_SUCCESS = 'CHAT_CONNECT_SUCCESS';
export const CHAT_CONNECT_ERROR = 'CHAT_CONNECT_ERROR';
export const CHAT_SET_MESSAGES = 'CHAT_SET_MESSAGES';
export const CHAT_SEND_MESSAGE_REQUEST = 'CHAT_SEND_MESSAGE_REQUEST';
export const CHAT_SEND_MESSAGE_SUCCESS = 'CHAT_SEND_MESSAGE_SUCCESS';
export const CHAT_SEND_MESSAGE_ERROR = 'CHAT_SEND_MESSAGE_ERROR';
