export const LOAD_TEMPLATES_LIST_REQUEST = 'LOAD_TEMPLATES_LIST_REQUEST';
export const LOAD_TEMPLATES_LIST_SUCCESS = 'LOAD_TEMPLATES_LIST_SUCCESS';
export const LOAD_TEMPLATES_LIST_ERROR = 'LOAD_TEMPLATES_LIST_ERROR';

export const LOAD_TEMPLATE_REQUEST = 'LOAD_TEMPLATE_REQUEST';
export const LOAD_TEMPLATE_SUCCESS = 'LOAD_TEMPLATE_SUCCESS';
export const LOAD_TEMPLATE_ERROR = 'LOAD_TEMPLATE_ERROR';
