export const SET_ACTIVE_TAB_ID = 'SET_ACTIVE_TAB_ID';
export const SET_FIELD_VALUE = 'SET_FIELD_VALUE';
export const VALIDATE_FIELD = 'VALIDATE_FIELD';
export const LOAD_FILE_REQUEST = 'LOAD_FILE_REQUEST';
export const LOAD_FILE_SUCCESS = 'LOAD_FILE_SUCCESS';
export const LOAD_FILE_ERROR = 'LOAD_FILE_ERROR';
